apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ $.Values.service.image | quote  }}
  name: {{ $.Values.service.image }}-service
spec:
  ports:
  - protocol: TCP
    port: 50051
  selector:
    app: {{ $.Values.service.image }}
---
